name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: docker://node:8
        with:
          entrypoint: yarn
          args: install --pure-lockfile --audit
      - uses: docker://node:8
        with:
          entrypoint: yarn
          args: lint
      - uses: docker://node:8
        with:
          entrypoint: yarn
          args: test
